### ISSUE TITLE
Create way to navigate by structured metadata

### ISSUE THREAD

**Issue by stevendungan** [grafana/explore-logs#310]
Currently, there is no option in the UI to explore [structured metadata](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/), or add structured metadata fields to queries.

Structured metadata is used for:
* transient, high cardinality infra labels (e.g. pod)
* OTel resource attributes which are not promoted to labels

<img width="801" alt="image" src="https://github.com/grafana/explore-logs/assets/114922977/0e00e359-5720-4e5d-b142-330f27995a35">

**Comment by ivanahuckova** [comment]
We should tackle this before GA, but the team does not think that another tab is a good solution - so we should explore the options.

**Comment by ivanahuckova** [comment]
@svennergr assigned this to you as you are working on structured metadata task.

**Comment by omri-shilton** [comment]
any estimate on when this will be fixed?

**Comment by omri-shilton** [comment]
@svennergr any news?

**Comment by trevorwhitney** [comment]
Structured metadata should be already be included in the detected fields pane, and in the response from Loki they are treated identically. I have noticed some problems in how we're determining which detected fields to show, that might be filtering out some of the structured metadata, but that should be fixed once we get the detected fields from the API in https://github.com/grafana/explore-logs/issues/678

**Comment by svennergr** [comment]
Solved by #736

**Comment by omri-shilton** [comment]
@svennergr @trevorwhitney I updated both grafana to 11.2 and explorelogs to 1.0.0 and it seems that this didnt solve my issue.
![Image](https://github.com/user-attachments/assets/c8e46785-798f-4bc9-915e-8a08faab84fc)

**Comment by trevorwhitney** [comment]
@omri-shilton do you see structured metadata and parsed fields in the logs view for this same service and time range?

**Comment by omri-shilton** [comment]
> @omri-shilton do you see structured metadata and parsed fields in the logs view for this same service and time range?

Yes

**Comment by trevorwhitney** [comment]
@omri-shilton would you mind opening a new issue, with as much detail as you can provide (ie. seeing the failed network requests would be useful).

**Comment by omri-shilton** [comment]
@trevorwhitney i already have an issue which was closed 
#486
