### ISSUE TITLE
Logs ingested with OTeL not showing detected_level and Detected Fields

### ISSUE THREAD

**Issue by omri-shilton** [grafana/explore-logs#486]
We use OTeL for our logs and it works great.
In the regular explore it automatically structures the attributes as metadata and identifies the level.
In explore:
<img width="1508" alt="image" src="https://github.com/grafana/explore-logs/assets/133574504/ef6b5d06-a6ce-45bb-8116-2a5aa38614c7">

In explore logs it doesnt:
<img width="1512" alt="image" src="https://github.com/grafana/explore-logs/assets/133574504/267b954a-c089-4a8b-af92-55866128d37d">
<img width="1512" alt="image" src="https://github.com/grafana/explore-logs/assets/133574504/24c94314-9562-4ede-a341-c540f7cfc954">

Are we doing something wrong?

**Comment by cyriltovena** [comment]
Structured metadata used by OTEL is not yet supported in Explore Logs but we're working on this actively. https://github.com/grafana/explore-logs/issues/310

**Comment by svennergr** [comment]
Thanks @omri-shilton. In Loki 3.0.0 we wrote the `level` label instead of `detected_level`. The PR that changed this behavior is https://github.com/grafana/loki/pull/12651 and is unfortunately not yet in a released version.

**Comment by omri-shilton** [comment]
@svennergr is this still related to the fact that im using OTeL? because I dont have a label level or detected_level. i didnt configure anything special other than the fact to listen to otel logs and im sending them like instructed here: https://grafana.com/docs/enterprise-logs/latest/send-data/otel/

**Comment by svennergr** [comment]
Yea, it's still related. I see the `level` label, which Loki automatically detected here:
![image](https://github.com/grafana/explore-logs/assets/8092184/9aa93c09-daca-4728-ac57-1431b5e7343a)

**Comment by omri-shilton** [comment]
Got it, im waiting for the PR on that fix. for now it doesnt even seem to have a PR.

**Comment by gtk-grafana** [comment]
Should be fixed by https://github.com/grafana/explore-logs/pull/736

**Comment by omri-shilton** [comment]
@gtk-grafana it appears that the fix did not solve my issue.

**Comment by svennergr** [comment]
Hi @omri-shilton,

As described, you would need to upgrade your Loki version to 3.2.0 which is the latest supported Loki version.

**Comment by omri-shilton** [comment]
@svennergr thanks, it works now
